meli:
  url: "https://api.mercadolibre.com/"

server:
  port: 8080

feign:
  client:
    config:
      meliClient:
        connectTimeout: 3000
        readTimeout: 10000
        loggerLevel: FULL

logging:
  level:
    com.coupon.restservice.client: DEBUG